events/lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/:id/event", EventController, :event
    resources "/comments", CommentController
    resources "/invitees", InviteeController
    
    resources "/sessions", SessionController, 
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

events/lib/events_web/templates/page/index.html.eex
<div class="row">
  <div class="col">
    <h1>Manage Events</h1>
    <%= link "Manage Events", to: Routes.event_path(@conn, :index) %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h1>Manage Users</h1>
    <%= link "Manage Users", to: Routes.user_path(@conn, :index) %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h1>Events Feed</h1>
    <%= if have_current_user?(@conn) do %>
      <span><%= link "New Event", to: Routes.event_path(@conn, :new) %></span>
    <% end %>
    <%= for event <- @events do %>
      <div class="col-sm-4 card">
        <div class="card-body">
          <p class="card-text"><%= event.name %></p>
          <%= link "view", to: Routes.event_path(@conn, :show, event) %>
        </div>
        <div class="card-body">
          <p>Created by <%= event.user.name %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>